server:
  port: 10087

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #      避免自己注册自己
#    register-with-eureka: false
    #    可以同步其它EurekaServer节点的数据，故设为false
    fetch-registry: true
  server:
    #  失效剔除
    eviction-interval-timer-in-ms: 30000
    #    自我保护
    enable-self-preservation: false

spring:
  application:
    name: eureka-server

  instance:
    lease-expiration-duration-in-seconds: 10 # 10秒即过期
    lease-renewal-interval-in-seconds: 5 # 5秒一次心跳
