server:
  port: 10010
spring:
  application:
    name: dj-zuul
zuul:
  routes:
    service-provider: /service-provider/**  # 这里是路由id，随意写
#      path: /service-provider/**
#      serviceId: service-provider
       # 这里是映射路径
    service-consumer: /service-consumer/**
  prefix: /api #  添加路由前缀
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka

