server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db3?serverTimezone=UTC
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: service-provider # 应用名称，注册到eureka后的服务名称
mybatis:
  type-aliases-package: com.dj.domain
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    service-url: # EurekaServer地址,多个地址以','隔开
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
